# Generated by Django 5.0.4 on 2024-04-16 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_auto_20210612_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 9, 47, 2, 118558)),
        ),
    ]
